{{- if contains "1.10" .Values.kyverno.image.tag -}}

  {{- $namespace := "" -}}
  {{- if .Values.namespace -}}
    {{- $namespace = .Values.namespace -}}
  {{- else -}}
      {{- $namespace = .Release.Namespace -}}
  {{- end -}}

  {{- $lookupResult := lookup "security.nirmata.io/v1alpha1" "Kyverno" $namespace "kyverno" -}}
  {{- if $lookupResult -}}
    {{- if not (contains "1.10" $lookupResult.spec.version) -}}
      {{- fail "upgrade from lower versions to 1.10 is not allowed. Please contact Nirmata's Customer Success team for assistance." -}}
    {{- end -}}
  {{- end -}}

{{- end -}}

{{- if .Values.kyverno.createCR }}
apiVersion: security.nirmata.io/v1alpha1
kind: Kyverno
metadata:
  annotations:
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
  name: kyverno
  namespace: {{ template "enterprise-kyverno.namespace" . }}
spec:
  secrets:
  
  namespace: {{ include "kyverno.namespace" . }}
  repository: {{ .Values.kyverno.image.repository }}
  version: {{ .Values.kyverno.image.tag }}
  replicas: {{ include "enterprise-kyverno.kyvernoReplicas" . }}

  helm:
    values:
      {{- toYaml .Values.kyverno.helm | nindent 6 }}
      cleanupController:
        image:
          tag: {{ .Values.kyverno.image.tag }}
      initImage:
        tag: {{ .Values.kyverno.image.tag }}
      {{- if and (eq .Values.kyverno.enablePolicyExceptions true) (contains "v1.9" .Values.kyverno.image.tag) }}
      extraArgs:
      - --enablePolicyException=true
      - --loggingFormat=text
      - --exceptionNamespace={{ include "kyverno.namespace" . }}
      {{- end }}
{{- end }}
