# Initialize oldVersion and NewVersion.
{{- $newVersion := .Values.kyverno.image.tag }}
{{- $oldVersion := "" }}

{{- $namespace := "" }}
{{- if .Values.namespace }}
  {{- $namespace = .Values.namespace }}
{{- else }}
    {{- $namespace = .Release.Namespace }}
{{- end }}

{{- $lookupResult := lookup "security.nirmata.io/v1alpha1" "Kyverno" $namespace "kyverno" }}
{{- if $lookupResult }}
  {{- $oldVersion = $lookupResult.spec.version }}
{{- end }}

# Prevent upgrade to breaking version "1.10".
{{- if contains "1.10" $newVersion }}
  {{- if not (contains "1.10" $oldVersion) }}
    {{- fail "upgrade from lower versions to 1.10 is not allowed. Please contact Nirmata's Customer Success team for assistance at support@nirmata.com." }}
  {{- end }}
{{- end }}

# Prevent skip upgrade.
{{- $oldVersionNumber := (split "." $oldVersion)[1] | int }}
{{- $newVersionNumber := (split "." $newVersion)[1] | int }}
{{- if gt $newVersionNumber (add $oldVersionNumber 1) }}
  {{- "skip upgrades are not allowed." }}
{{- end }}


{{- if .Values.kyverno.createCR }}
apiVersion: security.nirmata.io/v1alpha1
kind: Kyverno
metadata:
  annotations:
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
  name: kyverno
  namespace: {{ template "enterprise-kyverno.namespace" . }}
spec:
  secrets:
  
  namespace: {{ include "kyverno.namespace" . }}
  repository: {{ .Values.kyverno.image.repository }}
  version: {{ .Values.kyverno.image.tag }}
  replicas: {{ include "enterprise-kyverno.kyvernoReplicas" . }}

  helm:
    values:
      {{- toYaml .Values.kyverno.helm | nindent 6 }}
      cleanupController:
        image:
          tag: {{ .Values.kyverno.image.tag }}
      initImage:
        tag: {{ .Values.kyverno.image.tag }}
      {{- if and (eq .Values.kyverno.enablePolicyExceptions true) (contains "v1.9" .Values.kyverno.image.tag) }}
      extraArgs:
      - --enablePolicyException=true
      - --loggingFormat=text
      - --exceptionNamespace={{ include "kyverno.namespace" . }}
      {{- end }}
{{- end }}
