apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image-scan-adapter.fullname" . }}
  labels:
    {{- include "image-scan-adapter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "image-scan-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "image-scan-adapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        command:
        - /manager
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        image: {{ include "image-scan-adapter.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MEMORY_LIMIT
          value: "128"
        - name: MEMORY_MULTIPLIER
          value: "2.5"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /work
          name: work
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/run/docker.sock
          name: docker-socket
      serviceAccountName: {{ include "image-scan-adapter.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: work
      - emptyDir: {}
        name: tmp
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock

